FROM my_centos
RUN yum -y install ruby
RUN gem update
RUN gem install jekyll
RUN gem install jekyll-tagging
RUN gem install jekyll-sitemap
RUN gem install pygments.rb
RUN gem install redcarpet
RUN mkdir github && cd github && git clone https://github.com/wyman1024/wyman1024.github.io.jekyll-now.git blog
RUN cd github/blog && git pull && git checkout develop
